version: "2"

services:
  redis:
    image: redis:latest
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 whisper.asgi:application
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - redis
